### ISSUE TITLE
Is it possible to implement infinite scrolling with this plugin?

### ISSUE THREAD

**Issue by confile** [tothenew/Grails-Remote-Pagination-SampleApp#2]
Is it possible to implement infinite scrolling with this plugin? I mean that when the user scrolls down the page and the paginateButtons appear the pagination should be triggered automatically.

Can you provide some code for that?

**Comment by amitjain1982** [comment]
Currently it doesn't support change of records just on page scroll, however it does via click of a button i.e via pageScroll tag. I shall implement the feature requested as the time allows.

**Comment by confile** [comment]
This would be great. You would have the first Grails plugin that supports this feature and since this is very common these days on web sites, many people will use your plugin. I look forward to see this feature.

**Comment by amitjain1982** [comment]
I have released remote-pagination 0.4 version, which cover this request that non-stop page scroll. Please let me know if you face any issues or for any other feature request.

Thanks for your suggestion.

**Comment by confile** [comment]
@amitjain1982 That is great. I have three questions: 
1. Is it possible to set a default scroll position such that the new elements will be loaded when this line is reached?
2. Is it possible to save the paginated records in browser local storage for caching?
3. Wouldn't it be more efficient, if the new elements will be send as JSON?

**Comment by amitjain1982** [comment]
A1. Yes. You can specify heightOffset in pixels for the same. While scrolling it keeps checking if the distance from the page bottom is <= heightOffset and once reached it would get the next set of records.
A2. I feel this is not really in domain of remote-pagination. So would be difficult to incorporate. 
A3. Currently I don't see it as a need, as its benefit wouldn't be that noticeable and it would require list page to be designed differently as well.  

Having said that, for # 2 & # 3 patches are still welcome. 
Thanks
